[package]
name = "cmbr"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
wasm = ["dep:wasm-bindgen", "dep:js-sys"]

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
ordered-float = "5.5.0"
owo-colors = "4.4.0"
strum = { version = "0.28.0", features = ["derive"] }
wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }