use clap::Parser as ClapParser;
use cmbr::{
    checker::Checker,
    parser::{ASTNode, ASTNodeType, Parser, SpanType},
    tokenizer::Tokenizer,
    treewalker::{Treewalker, Type},
    types::{
        CLIInterpreterIO, DiagType, Diagnostic, DiagnosticPrinter, ErrType, Failure, Info, Stage,
    },
};
use inquire::Select;
use owo_colors::OwoColorize;
use std::path::PathBuf;
use std::{fs::File, io::Read, process::exit};

fn main() {
    let cli = Cli::parse();
    let mut buf = String::new();
    match File::open(&cli.path) {
        Ok(mut f) => match f.read_to_string(&mut buf) {
            Ok(v) => v,
            Err(e) => {
                eprintln!("{}{}", "error".red().bold(), format!(": {}", e.bold()));
                exit(1)
            }
        },
        Err(e) => {
            eprintln!("{}{}", "error".red().bold(), format!(": {}", e.bold()));
            exit(1);
        }
    };

    let fp = cli.path.to_string_lossy();
    let tk = Tokenizer::new(buf.clone(), fp.clone());
    let diag_printer: DiagnosticPrinter<CLIInterpreterIO> =
        DiagnosticPrinter::new(buf, CLIInterpreterIO);
    let mut tkns = Vec::new();
    for tkn in tk {
        match tkn {
            Ok(v) => {
                if let Some(tkn) = v {
                    tkns.push(tkn)
                }
            }
            Err(e) => {
                diag_printer.print_diagnostic(&e);
                if e.is_critical() {
                    exit(1)
                }
            }
        }
    }

    let psr = Parser::new(tkns, fp);
    let mut ast = Vec::new();

    for node in psr {
        match node {
            Ok(n) => ast.push(n),
            Err(e) => {
                diag_printer.print_diagnostic(&e);
                if e.is_critical() {
                    exit(1)
                }
            }
        }
    }
    let mut f: Option<Box<dyn FnMut(String) -> Result<cmbr::treewalker::Type, Diagnostic>>>;
    if cli.interactive {
        f = Some(Box::new(|v| {
            let prompt = format!("select a type for variable {v}");
            let c = Select::new(
                &prompt,
                vec![Type::Int, Type::String, Type::Real, Type::Bool, Type::Char],
            );
            match c.prompt() {
                Ok(v) => Ok(v),
                Err(e) => Err(Diagnostic {
                    ty: DiagType::Err(
                        ErrType::Other {
                            msg: format!("error while asking type for {v}: {e}"),
                        },
                        Stage::Checker,
                    ),
                    info: vec![Info::note(
                        "there is nothing wrong with your program. Instead, there is something wrong with your environment",
                    )],
                    span: None,
                }),
            }
        }));
    } else {
        f = None
    }
    
    let mut checker = Checker::new(f);
    let mut failed = false;

    for node in &ast {
        if let Err(e) = checker.check_node(&node.clone()) {
            diag_printer.print_diagnostic(&e);
            if e.is_critical() {
                failed = true;
            }
        }
    }
    if failed {
        exit(1)
    }
    for (ident, ty) in checker.generated_decls {
        ast.insert(
            0,
            ASTNode {
                ty: ASTNodeType::Declare { ident, ty },
                span: SpanType::AutoGenerated,
            },
        )
    }
    println!("{}", "---- running ----".bright_black());
    let mut walker = Treewalker::new(&ast, CLIInterpreterIO);
    if let Err(e) = walker.run() {
        diag_printer.print_diagnostic(&e);
        exit(1)
    };
}

#[derive(ClapParser)]
#[command(version, about, long_about = None)]
struct Cli {
    path: PathBuf,
    #[arg(short, long)]
    interactive: bool,
    #[arg(short, long, requires = "interactive")]
    rewrite: bool,
}
