name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry and build
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --release --verbose

      - name: Build
        run: cargo build --release --verbose

      - name: Rename Windows binary
        shell: bash
        if: matrix.os == 'windows-latest'
        run: mv target/release/cmbr.exe target/release/cmbr-windows-latest-x86_64.exe
        
      - name: Rename UNIX binary
        if: matrix.os != 'windows-latest'
        run: mv target/release/cmbr.exe target/release/cmbr-${{ matrix.os }}-x86_64.exe

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: release-bins
          path: target/release/cmbr-windows-latest-x86_64.exe
          if-no-files-found: error

      - name: Upload UNIX binary
        uses: actions/upload-artifact@v4
        if: matrix.os != 'windows-latest'
        with:
          name: release-bins
          path: target/release/cmbr-${{ matrix.os }}-x86_64
          if-no-files-found: error  
    
  create-draft-release:
    name: Create Draft Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - uses: actions/checkout@v4

      
      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          name: release-binaries
          path: release-assets/

      - name: Create Draft GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}